DROP TABLE IF EXISTS "USERS";

CREATE TABLE "USERS" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "USERNAME" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "ROLE" VARCHAR(255) NOT NULL,
    "LAST_ONLINE" TIMESTAMP,
    "PROFILE_PICTURE_URL" VARCHAR(255)
);
